version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose Django application port
    volumes:
      - ./app:/app  # Mount Django application code

  nginx:
    image: nginx
    ports:
      - "80:80"  # Expose Nginx port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount Nginx configuration
    depends_on:
      - django
