# Generated by Django 4.2.1 on 2023-09-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelsior', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='article_images_additional')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelsior.articles')),
            ],
        ),
    ]
