# Generated by Django 4.2.1 on 2023-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelsior', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Top', max_length=30),
        ),
    ]
