# Generated by Django 4.2.1 on 2023-10-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelsior', '0005_alter_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
